/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesApArRouteImport } from './routes/services.ap-ar'
import { Route as ServicesCatchUpCleanupRouteImport } from './routes/services.catch-up-cleanup'
import { Route as ServicesFinancialStatementsRouteImport } from './routes/services.financial-statements'
import { Route as ServicesMonthlyBookkeepingRouteImport } from './routes/services.monthly-bookkeeping'
import { Route as ServicesReconciliationRouteImport } from './routes/services.reconciliation'
import { Route as ServicesSalesTaxYearEndRouteImport } from './routes/services.sales-tax-year-end'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesApArRoute = ServicesApArRouteImport.update({
  id: '/ap-ar',
  path: '/ap-ar',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCatchUpCleanupRoute = ServicesCatchUpCleanupRouteImport.update({
  id: '/catch-up-cleanup',
  path: '/catch-up-cleanup',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFinancialStatementsRoute =
  ServicesFinancialStatementsRouteImport.update({
    id: '/financial-statements',
    path: '/financial-statements',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMonthlyBookkeepingRoute =
  ServicesMonthlyBookkeepingRouteImport.update({
    id: '/monthly-bookkeeping',
    path: '/monthly-bookkeeping',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesReconciliationRoute = ServicesReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSalesTaxYearEndRoute = ServicesSalesTaxYearEndRouteImport.update({
  id: '/sales-tax-year-end',
  path: '/sales-tax-year-end',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ap-ar': typeof ServicesApArRoute
  '/services/catch-up-cleanup': typeof ServicesCatchUpCleanupRoute
  '/services/financial-statements': typeof ServicesFinancialStatementsRoute
  '/services/monthly-bookkeeping': typeof ServicesMonthlyBookkeepingRoute
  '/services/reconciliation': typeof ServicesReconciliationRoute
  '/services/sales-tax-year-end': typeof ServicesSalesTaxYearEndRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/services/ap-ar': typeof ServicesApArRoute
  '/services/catch-up-cleanup': typeof ServicesCatchUpCleanupRoute
  '/services/financial-statements': typeof ServicesFinancialStatementsRoute
  '/services/monthly-bookkeeping': typeof ServicesMonthlyBookkeepingRoute
  '/services/reconciliation': typeof ServicesReconciliationRoute
  '/services/sales-tax-year-end': typeof ServicesSalesTaxYearEndRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/ap-ar': typeof ServicesApArRoute
  '/services/catch-up-cleanup': typeof ServicesCatchUpCleanupRoute
  '/services/financial-statements': typeof ServicesFinancialStatementsRoute
  '/services/monthly-bookkeeping': typeof ServicesMonthlyBookkeepingRoute
  '/services/reconciliation': typeof ServicesReconciliationRoute
  '/services/sales-tax-year-end': typeof ServicesSalesTaxYearEndRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/onboarding'
    | '/pricing'
    | '/services'
    | '/services/ap-ar'
    | '/services/catch-up-cleanup'
    | '/services/financial-statements'
    | '/services/monthly-bookkeeping'
    | '/services/reconciliation'
    | '/services/sales-tax-year-end'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/onboarding'
    | '/pricing'
    | '/services/ap-ar'
    | '/services/catch-up-cleanup'
    | '/services/financial-statements'
    | '/services/monthly-bookkeeping'
    | '/services/reconciliation'
    | '/services/sales-tax-year-end'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/onboarding'
    | '/pricing'
    | '/services'
    | '/services/ap-ar'
    | '/services/catch-up-cleanup'
    | '/services/financial-statements'
    | '/services/monthly-bookkeeping'
    | '/services/reconciliation'
    | '/services/sales-tax-year-end'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ap-ar': {
      id: '/services/ap-ar'
      path: '/ap-ar'
      fullPath: '/services/ap-ar'
      preLoaderRoute: typeof ServicesApArRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/catch-up-cleanup': {
      id: '/services/catch-up-cleanup'
      path: '/catch-up-cleanup'
      fullPath: '/services/catch-up-cleanup'
      preLoaderRoute: typeof ServicesCatchUpCleanupRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/financial-statements': {
      id: '/services/financial-statements'
      path: '/financial-statements'
      fullPath: '/services/financial-statements'
      preLoaderRoute: typeof ServicesFinancialStatementsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/monthly-bookkeeping': {
      id: '/services/monthly-bookkeeping'
      path: '/monthly-bookkeeping'
      fullPath: '/services/monthly-bookkeeping'
      preLoaderRoute: typeof ServicesMonthlyBookkeepingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/reconciliation': {
      id: '/services/reconciliation'
      path: '/reconciliation'
      fullPath: '/services/reconciliation'
      preLoaderRoute: typeof ServicesReconciliationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/sales-tax-year-end': {
      id: '/services/sales-tax-year-end'
      path: '/sales-tax-year-end'
      fullPath: '/services/sales-tax-year-end'
      preLoaderRoute: typeof ServicesSalesTaxYearEndRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesApArRoute: typeof ServicesApArRoute
  ServicesCatchUpCleanupRoute: typeof ServicesCatchUpCleanupRoute
  ServicesFinancialStatementsRoute: typeof ServicesFinancialStatementsRoute
  ServicesMonthlyBookkeepingRoute: typeof ServicesMonthlyBookkeepingRoute
  ServicesReconciliationRoute: typeof ServicesReconciliationRoute
  ServicesSalesTaxYearEndRoute: typeof ServicesSalesTaxYearEndRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesApArRoute: ServicesApArRoute,
  ServicesCatchUpCleanupRoute: ServicesCatchUpCleanupRoute,
  ServicesFinancialStatementsRoute: ServicesFinancialStatementsRoute,
  ServicesMonthlyBookkeepingRoute: ServicesMonthlyBookkeepingRoute,
  ServicesReconciliationRoute: ServicesReconciliationRoute,
  ServicesSalesTaxYearEndRoute: ServicesSalesTaxYearEndRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
